---
name: main

on:
  pull_request:
  release:
    types: [published]

jobs:
  tests:
    name: Tests
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            python: 3.6
            toxenv: py
          - os: ubuntu-latest
            python: 3.7
            toxenv: py
          - os: ubuntu-latest
            python: 3.8
            toxenv: py
          - os: ubuntu-latest
            python: 3.9
            toxenv: py
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: Set Python up
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
          # Disable shallow clone for Sonar scanner, as it needs access to the history
          fetch-depth: 0
      - name: Install testing tools
        run: python -m pip install --upgrade setuptools pip tox virtualenv coverage
      - name: Run the tests
        run: tox -e ${{ matrix.toxenv }}
      - name: Combine Coverage reports
        run: coverage combine
      - name: Generage Coverage combined XML report
        run: coverage xml
      - name: SonarCloud scanning
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >-
            -Dsonar.projectKey=${{ github.repository_owner }}_${{ github.event.repository.name }}
            -Dsonar.organization=${{ github.repository_owner }}

  pypi-publish:
    name: Publish to PyPi
    runs-on: ubuntu-latest
    needs: [tests]
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # `setuptools_scm` needs tags
      - name: Set Python up
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install the PEP517 package builder
        run: python -m pip install --upgrade build
      - name: Build the package
        run: python -m build
      - name: Publish the package to Test PyPi
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.TEST_PYPI_TOKEN }}
          repository_url: https://test.pypi.org/legacy/
      - name: Publish the release to PyPi
        if: github.event_name == 'release' && github.event.action == 'published'
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
